---
  # Talk to all hosts just so we can learn about them...
- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: sss 
    instance_type: t2.micro
    image: ami-76d6f519
    region: ap-south-1
    access: AKIAJKKK4HFE7SNCWCPQ
    secret: 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
    count: 3 
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ keypair }}"
         group: default
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         aws_access_key: "{{ access }}"
         aws_secret_key: "{{ secret }}"
         count: "{{ count }}"
      register: ec2
    - name: Print all ec2 variables
      debug: var=ec2

